# Generated by Django 3.2.6 on 2021-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_customer', to='shopserver.Order', verbose_name='Заказы покупателя'),
        ),
    ]
