# Generated by Django 3.2.6 on 2021-08-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopserver', '0002_alter_customer_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
