# Generated by Django 3.2.6 on 2021-08-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopserver', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopserver.sizeproduct', verbose_name='Размер'),
        ),
    ]
