# Generated by Django 3.2.6 on 2021-08-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopserver', '0006_auto_20210826_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='shopserver.Order', verbose_name='Заказы покупателя'),
        ),
    ]
